export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function MovieLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="movie-layout">
      {children}
    </div>
  );
}

